### ISSUE TITLE
Sentry causes permissions errors when players are within proximity

### ISSUE THREAD

**Issue by Craigdb** [jrbudda/Sentry#23]
I have performed a few tests on this error as it started spamming the server as soon as I created the Sentry (ie the moment I set the trait on the NPC)... after a while I moved away from the npc and tried... it turns out the errors only happen when a player is within range of the NPC. I am running all the recommended builds on the page (S0.9.6 & Cit b345... and permissionsbukkit 2.0 (as it is the primary error listed). 

Any help appreciated here, thanks.

Here is my error:

2012-09-12 20:01:27 [WARNING] [Sentry] Task #46 for Sentry v0.9.6 generated an exception
java.lang.NoSuchMethodError: com.platymuus.bukkit.permissions.PermissionInfo.getWorlds()Ljava/util/List;
    at net.milkbowl.vault.permission.plugins.Permission_PermissionsBukkit.getPlayerGroups(Permission_PermissionsBukkit.java:194)
    at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:513)
    at net.aufdemrand.sentry.SentryInstance._checkTarget(SentryInstance.java:448)
    at net.aufdemrand.sentry.SentryInstance.findTarget(SentryInstance.java:350)
    at net.aufdemrand.sentry.SentryInstance$SentryLogicRunnable.run(SentryInstance.java:183)
    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:52)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:316)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:510)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

This error spams the console until no players are within range of the Sentry NPC

**Comment by jrbudda** [comment]
That appears to be an issue between Vault and PermissionsBukkit. Sentry does not communicate with PermissionsBukkit directly.

**Comment by Craigdb** [comment]
I have updated Vault... thanks very much... btw I set the sentry to entity:all and strength 100 - was enough to make very entertaining for a first test. Thanks again.
